---
- hosts: clientservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    dnf:
      name: "*"
      state: latest
  - name: ensure apache is at the latest version
    dnf:
      name: "*"
      state: latest
