---
- hosts: clientservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: update client packages
    dnf:
      name: "*"
      state: latest
  - name: reboot server
    dnf:
      name: "*"
      state: latest
