---
- hosts: clientservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  
  tasks:
  
  - name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  
 - name: reboot all clients
  reboot:

